version: 0.2  # Corrected version
phases:
  install:
    commands:
      - npm install --silent
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket awsloging --output-template-file output-template.yaml
artifacts:
  files:
    - '**/*'
