AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda NodeJS starter project

Parameters:

  LambdaName:
    Description: "login1"
    Type: "String"

  LambdaDescription:
    Description: "login logic"
    Type: "String"

  LambdaRole:
    Description: arn:aws:iam::730335543189:role/lambdafunction
    Type: "String"
    Default: ""

Resources:
  LambdaInstagramWrapper:
    Type: 'AWS::Lambda::Function'
    Properties:
      Role: arn:aws:iam::730335543189:role/lambdafunction
      FunctionName: 'login2'
      MemorySize: 512
      Timeout: 60
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: .
      Description: !Ref LambdaDescription